# Generated by Django 3.2.7 on 2023-05-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=40)),
                ('Contact', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
