# Generated by Django 3.2.7 on 2023-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230509_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Dob',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
